FROM alpine:latest

USER root
RUN   apk update \
      && apk add \
        && erlang \
        && sudo \
        && node \
        && elixir \

RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez

